ARG SKYMAP_SCANNER_VERSION=latest

FROM icecube/skymap_scanner:$SKYMAP_SCANNER_VERSION as prod


RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/InfBareMu_mie_abs_z20a10_V2.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/InfBareMu_mie_abs_z20a10_V2.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/InfBareMu_mie_prob_z20a10_V2.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/InfBareMu_mie_prob_z20a10_V2.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/cascade_single_spice_ftp-v1_flat_z20_a5.abs.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/cascade_single_spice_ftp-v1_flat_z20_a5.abs.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/cascade_single_spice_ftp-v1_flat_z20_a5.prob.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/cascade_single_spice_ftp-v1_flat_z20_a5.prob.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/cascade_effectivedistance_spice_ftp-v1_z20.eff.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/cascade_effectivedistance_spice_ftp-v1_z20.eff.fits

ENV OPENBLAS_CORETYPE="Haswell"
ENV NPY_DISABLE_CPU_FEATURES="AVX512F,AVX512_KNL,AVX512_KNM,AVX512_CLX,AVX512_CNL,AVX512_ICL,AVX512CD,AVX512_SKX"

ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh"]

CMD []
