ARG SKYMAP_SCANNER_VERSION=latest

FROM icecube/skymap_scanner:$SKYMAP_SCANNER_VERSION AS prod


RUN mkdir -p /opt/i3-data/baseline_gcds && \
    wget -nv -N -t 5 -P /opt/i3-data/baseline_gcds -r -l 1 -A *.i3* -nd http://prod-exe.icecube.wisc.edu/baseline_gcds/ && \
    chmod -R u+rwX,go+rX,go-w /opt/i3-data/baseline_gcds

RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/InfBareMu_mie_abs_z20a10_V2.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/InfBareMu_mie_abs_z20a10_V2.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/InfBareMu_mie_prob_z20a10_V2.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/InfBareMu_mie_prob_z20a10_V2.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/cascade_single_spice_ftp-v1_flat_z20_a5.abs.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/cascade_single_spice_ftp-v1_flat_z20_a5.abs.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/cascade_single_spice_ftp-v1_flat_z20_a5.prob.v2.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/cascade_single_spice_ftp-v1_flat_z20_a5.prob.v2.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/cascade_effectivedistance_spice_ftp-v1_z20.eff.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/cascade_effectivedistance_spice_ftp-v1_z20.eff.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/cascade_effectivedistance_spice_ftp-v1_z20.prob.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/cascade_effectivedistance_spice_ftp-v1_z20.prob.fits
RUN wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/cascade_effectivedistance_spice_ftp-v1_z20.tmod.fits \
       http://prod-exe.icecube.wisc.edu/spline-tables/cascade_effectivedistance_spice_ftp-v1_z20.tmod.fits

ENV OPENBLAS_CORETYPE="Haswell"
ENV NPY_DISABLE_CPU_FEATURES="AVX512F,AVX512_KNL,AVX512_KNM,AVX512_CLX,AVX512_CNL,AVX512_ICL,AVX512CD,AVX512_SKX"

ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh"]

CMD []
