#!/bin/sh

# docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00118178.i3.zst -n Run00118178 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,1465) [llh=1235.02]: dec=-2.39deg RA=140.62deg / 9.38hours 

# docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00118309.i3.zst -n Run00118309 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,2448) [llh=2407.48]: dec=35.69deg RA=272.81deg / 18.19hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118342.i3.zst -n Run00118342 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,1644) [llh=1145.85]: dec=4.78deg RA=70.31deg / 4.69hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118475.i3.zst -n Run00118475 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,1723) [llh=1797.48]: dec=7.18deg RA=151.88deg / 10.12hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118539.i3.zst -n Run00118539 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,1628) [llh=1298.03]: dec=2.39deg RA=337.50deg / 22.50hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118576.i3.zst -n Run00118576 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,1499) [llh=2460.25]: dec=-2.39deg RA=331.88deg / 22.13hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00118631.i3.zst -n Run00118631 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,1698) [llh=1199.89]: dec=7.18deg RA=11.25deg / 0.75hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00118660.i3.zst -n Run00118660 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,1794) [llh=1095.63]: dec=9.59deg RA=194.06deg / 12.94hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118738.i3.zst -n Run00118738 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,2725) [llh=3296.28]: dec=51.26deg RA=121.15deg / 8.08hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118741.i3.zst -n Run00118741 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,1423) [llh=2344.50]: dec=-4.78deg RA=267.19deg / 17.81hours 

#docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118778.i3.zst -n Run00118778 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
- DONE: at (nside,pix)=(16,2620) [llh=2039.88]: dec=44.99deg RA=171.00deg / 11.40hours 



docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118973.i3.zst -n Run00118973 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00118973.i3.zst -n Run00118973 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00119097.i3.zst -n Run00119097 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00119101.i3.zst -n Run00119101 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00119125.i3.zst -n Run00119125 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00119136.i3.zst -n Run00119136 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00119146.i3.zst -n Run00119146 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00119739.i3.zst -n Run00119739 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120027.i3.zst -n Run00120027 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00120157.i3.zst -n Run00120157 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120185.i3.zst -n Run00120185 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120186.i3.zst -n Run00120186 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120205.i3.zst -n Run00120205 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120244.i3.zst -n Run00120244 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120260.i3.zst -n Run00120260 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120309.i3.zst -n Run00120309 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00120535.i3.zst -n Run00120535 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00120680.i3.zst -n Run00120680 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00120798.i3.zst -n Run00120798 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00120860.i3.zst -n Run00120860 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120884.i3.zst -n Run00120884 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00120935.i3.zst -n Run00120935 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00121761.i3.zst -n Run00121761 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00121762.i3.zst -n Run00121762 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00121769.i3.zst -n Run00121769 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122055.i3.zst -n Run00122055 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122060.i3.zst -n Run00122060 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122154.i3.zst -n Run00122154 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122160.i3.zst -n Run00122160 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122316.i3.zst -n Run00122316 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122318.i3.zst -n Run00122318 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122361.i3.zst -n Run00122361 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122469.i3.zst -n Run00122469 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00122604.i3.zst -n Run00122604 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122605.i3.zst -n Run00122605 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122663.i3.zst -n Run00122663 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122768.i3.zst -n Run00122768 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122772.i3.zst -n Run00122772 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122793.i3.zst -n Run00122793 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122818.i3.zst -n Run00122818 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00122895.i3.zst -n Run00122895 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00123107.i3.zst -n Run00123107 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00123145.i3.zst -n Run00123145 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00123228.i3.zst -n Run00123228 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00123240.i3.zst -n Run00123240 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00123281.i3.zst -n Run00123281 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00123365.i3.zst -n Run00123365 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00123620.i3.zst -n Run00123620 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00123662.i3.zst -n Run00123662 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00123751.i3.zst -n Run00123751 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00123762.i3.zst -n Run00123762 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00123986.i3.zst -n Run00123986 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124221.i3.zst -n Run00124221 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124296.i3.zst -n Run00124296 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124340.i3.zst -n Run00124340 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124463.i3.zst -n Run00124463 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00124547.i3.zst -n Run00124547 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124569.i3.zst -n Run00124569 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124643.i3.zst -n Run00124643 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124693.i3.zst -n Run00124693 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124829.i3.zst -n Run00124829 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00124852.i3.zst -n Run00124852 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00124861.i3.zst -n Run00124861 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00124994.i3.zst -n Run00124994 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00125001.i3.zst -n Run00125001 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125011.i3.zst -n Run00125011 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125046.i3.zst -n Run00125046 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125205.i3.zst -n Run00125205 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125338.i3.zst -n Run00125338 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00125349.i3.zst -n Run00125349 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125422.i3.zst -n Run00125422 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125558.i3.zst -n Run00125558 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125693.i3.zst -n Run00125693 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125757.i3.zst -n Run00125757 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125796.i3.zst -n Run00125796 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125800.i3.zst -n Run00125800 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125929.i3.zst -n Run00125929 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125934.i3.zst -n Run00125934 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125940.i3.zst -n Run00125940 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00125968.i3.zst -n Run00125968 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00125973.i3.zst -n Run00125973 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126082.i3.zst -n Run00126082 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126148.i3.zst -n Run00126148 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126308.i3.zst -n Run00126308 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00126370.i3.zst -n Run00126370 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126405.i3.zst -n Run00126405 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126423.i3.zst -n Run00126423 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126456.i3.zst -n Run00126456 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126456.i3.zst -n Run00126456 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126514.i3.zst -n Run00126514 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126515.i3.zst -n Run00126515 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00126620.i3.zst -n Run00126620 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126703.i3.zst -n Run00126703 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126717.i3.zst -n Run00126717 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00126718.i3.zst -n Run00126718 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126769.i3.zst -n Run00126769 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00126798.i3.zst -n Run00126798 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00126812.i3.zst -n Run00126812 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126848.i3.zst -n Run00126848 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126860.i3.zst -n Run00126860 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00126863.i3.zst -n Run00126863 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126878.i3.zst -n Run00126878 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126911.i3.zst -n Run00126911 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00126976.i3.zst -n Run00126976 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00126989.i3.zst -n Run00126989 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00127112.i3.zst -n Run00127112 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00127154.i3.zst -n Run00127154 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00127357.i3.zst -n Run00127357 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00127603.i3.zst -n Run00127603 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00127650.i3.zst -n Run00127650 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00127742.i3.zst -n Run00127742 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00127790.i3.zst -n Run00127790 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00127910.i3.zst -n Run00127910 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128034.i3.zst -n Run00128034 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128065.i3.zst -n Run00128065 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128067.i3.zst -n Run00128067 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128209.i3.zst -n Run00128209 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128253.i3.zst -n Run00128253 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128278.i3.zst -n Run00128278 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128292.i3.zst -n Run00128292 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00128311.i3.zst -n Run00128311 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128334.i3.zst -n Run00128334 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00128547.i3.zst -n Run00128547 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00128567.i3.zst -n Run00128567 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00128606.i3.zst -n Run00128606 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128632.i3.zst -n Run00128632 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128651.i3.zst -n Run00128651 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00128755.i3.zst -n Run00128755 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128785.i3.zst -n Run00128785 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128796.i3.zst -n Run00128796 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00128967.i3.zst -n Run00128967 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00129020.i3.zst -n Run00129020 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129144.i3.zst -n Run00129144 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129153.i3.zst -n Run00129153 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129154.i3.zst -n Run00129154 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129267.i3.zst -n Run00129267 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129420.i3.zst -n Run00129420 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129434.i3.zst -n Run00129434 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129506.i3.zst -n Run00129506 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00129506.i3.zst -n Run00129506 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129550.i3.zst -n Run00129550 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129654.i3.zst -n Run00129654 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00129677.i3.zst -n Run00129677 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00129701.i3.zst -n Run00129701 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00129777.i3.zst -n Run00129777 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00129855.i3.zst -n Run00129855 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00129878.i3.zst -n Run00129878 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00129915.i3.zst -n Run00129915 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00129933.i3.zst -n Run00129933 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00130033.i3.zst -n Run00130033 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00130034.i3.zst -n Run00130034 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130092.i3.zst -n Run00130092 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130172.i3.zst -n Run00130172 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00130214.i3.zst -n Run00130214 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130220.i3.zst -n Run00130220 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00130588.i3.zst -n Run00130588 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130597.i3.zst -n Run00130597 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130639.i3.zst -n Run00130639 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130684.i3.zst -n Run00130684 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130743.i3.zst -n Run00130743 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130797.i3.zst -n Run00130797 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130801.i3.zst -n Run00130801 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00130807.i3.zst -n Run00130807 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00130912.i3.zst -n Run00130912 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00130932.i3.zst -n Run00130932 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131096.i3.zst -n Run00131096 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131134.i3.zst -n Run00131134 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131145.i3.zst -n Run00131145 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131165.i3.zst -n Run00131165 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131321.i3.zst -n Run00131321 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131360.i3.zst -n Run00131360 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131477.i3.zst -n Run00131477 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131505.i3.zst -n Run00131505 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131519.i3.zst -n Run00131519 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131602.i3.zst -n Run00131602 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131653.i3.zst -n Run00131653 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00131746.i3.zst -n Run00131746 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00131764.i3.zst -n Run00131764 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00131767.i3.zst -n Run00131767 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00131768.i3.zst -n Run00131768 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00132043.i3.zst -n Run00132043 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00132128.i3.zst -n Run00132128 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer   http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_gold/Run00132206.i3.zst -n Run00132206 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
docker run --rm -ti icecube/skymap_scanner:latest producer http://icecube:skua@convey.icecube.wisc.edu/data/user/tkintscher/samples/gfu_2017/i3/muons_bronze/Run00132237.i3.zst -n Run00132237 --broker pulsar+ssl://pulsar.api.icecube.aq:6651 --nside 16 --auth-token `cat aws_ec2/pulsar_terraform_ansible/secrets/icecube.skymap.token`
