name: dump-scan-logs

description: Dump server/worker/client outputs for a skymap_scanner CI run

inputs:
  outdir:
    description: Directory where server/worker logs are written
    required: true
  n-workers:
    description: Number of workers to dump (usually 1 or 2)
    required: false
    default: "2"

runs:
  using: composite
  steps:
    - name: "dump output — central server stdout/stderr"
      if: always()
      shell: bash
      run: |
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        echo "::group::central server stdout/stderr"
        cat "${{ inputs.outdir }}/server.out" || true
        echo "::endgroup::"

    - name: "dump output — worker pilot #1 stdout/stderr"
      if: always()
      shell: bash
      run: |
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        echo "::group::worker-1 pilot stdout/stderr"
        more "${{ inputs.outdir }}/worker-1/pilot.out" | cat || true
        echo "::endgroup::"

    - name: "dump output — worker clients / reco-icetray instances #1 stdouts/stderrs"
      if: always()
      shell: bash
      run: |
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        echo "::group::worker-1 client stdouts/stderrs"
        find "${{ inputs.outdir }}/worker-1/pilot-"* \
          -name "stderrfile" -o -name "stdoutfile" \
          | xargs --no-run-if-empty more | cat || true
        echo "::::::::::::::" && (tree "${{ inputs.outdir }}/worker-1/pilot-"* || true)
        echo "::endgroup::"

    - name: "dump output — worker pilot #2 stdout/stderr (if present)"
      if: ${{ always() && inputs['n-workers'] == '2' }}
      shell: bash
      run: |
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        echo "::group::worker-2 pilot stdout/stderr"
        more "${{ inputs.outdir }}/worker-2/pilot.out" | cat || true
        echo "::endgroup::"

    - name: "dump output — worker clients / reco-icetray instances #2 stdouts/stderrs (if present)"
      if: ${{ always() && inputs['n-workers'] == '2' }}
      shell: bash
      run: |
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        echo "::group::worker-2 client stdouts/stderrs"
        find "${{ inputs.outdir }}/worker-2/pilot-"* \
          -name "stderrfile" -o -name "stdoutfile" \
          | xargs --no-run-if-empty more | cat || true
        echo "::::::::::::::" && (tree "${{ inputs.outdir }}/worker-2/pilot-"* || true)
        echo "::endgroup::"

    - name: RabbitMQ diagnostics
      if: always()
      shell: bash
      run: |
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"

        echo "::group::docker logs (rabbitmq)"
        docker logs rabbitmq || true
        echo "::endgroup::"

        echo "::group::rabbitmqctl status"
        docker exec rabbitmq rabbitmqctl status || true
        echo "::endgroup::"

        echo "::group::rabbitmq-diagnostics memory"
        docker exec rabbitmq rabbitmq-diagnostics memory || true
        echo "::endgroup::"

        echo "::group::rabbitmq-diagnostics environment"
        docker exec rabbitmq rabbitmq-diagnostics environment || true
        echo "::endgroup::"

        echo "::group::rabbitmq-diagnostics alarms"
        docker exec rabbitmq rabbitmq-diagnostics alarms || true
        echo "::endgroup::"
