name: scan-setup
description: Common CI setup for skymap_scanner tests (disk space, checkout, Docker build)
inputs:
  ref:
    description: Git ref to checkout
    required: true
  docker-tag:
    description: Local Docker tag to build
    required: true
  free-disk-space:
    description: Run free-disk-space step (true/false)
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: "— Disk Space —"
      if: always()
      shell: bash
      run: df -h /

    - name: free disk space (optional)
      if: ${{ inputs.free-disk-space == 'true' }}
      uses: Jayllyz/free-disk-space@3bda29d61d3f1fa7bf46c5a9a11f22dd20af07c9
      with:
        docker-images: false

    - name: "— Disk Space —"
      if: ${{ inputs.free-disk-space == 'true' }}
      shell: bash
      run: df -h /

    - uses: docker/setup-buildx-action@v3

    - uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ inputs.docker-tag }}
        load: true
