name: Build Skymap Scanner Image (checkout + buildx + build)

inputs:
  image-tag:
    description: 'Docker image tag to apply (e.g., ${{ env._SCANNER_IMAGE_DOCKER }}).'
    required: true
  load:
    description: '"true" to load into the local Docker daemon; "false" for build-only.'
    required: true
  include-gcd:
    description: '"1" to include GCD files; "0" to skip.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository (locked to ${{ github.sha }})
      uses: actions/checkout@v5
      with:
        ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
        fetch-depth: 0  # setuptools-scm needs to access git tag

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ inputs.image-tag }}
        load: ${{ inputs.load }}
        build-args: INCLUDE_GCD=${{ inputs.include-gcd }}
