name: tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  PY_COLORS: "1"
  REALTIME_EVENTS_DIR: tests/data/realtime_events
  PULSAR_CONTAINER: pulsar_local
  SKYSCAN_CACHE_DIR: cache-dir
  SKYSCAN_OUTPUT_DIR: output-dir
  PULSAR_ADDRESS: localhost:6650
  PULSAR_AUTH: ""
  SKYSCAN_DEBUG_DIR: debug-pkl-dir
  SKYSCAN_REPORT_INTERVAL_SEC: 60
  CI_TESTING_USE_LOCAL_DOCKER: 1

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          ./tests/docker_scripts/docker_local_build.sh

  test-run-all:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        eventfile: [
          hese_event_01.json,
          run00136766-evt000007637140-GOLD.pkl,
          run00136662-evt000035405932-BRONZE.pkl
        ]
    env:
      CLIENTS_PER_CPU: 1  # there isn't any improvement when >1
    steps:
      - uses: actions/checkout@v3
      - name: Run Pulsar Server Docker Container (starts up during skymap scanner image build)
        run: |
          ./scripts/launch_scripts/pulsar_run.sh $PULSAR_CONTAINER
      - name: Build Skymap Scanner Docker Image
        run: |
          ./tests/docker_scripts/docker_local_build.sh
      - name: Configure Pulsar Server
        run: |
          ./tests/docker_scripts/pulsar_config.sh $PULSAR_CONTAINER
      - name: Run
        run: |

          mkdir $GITHUB_WORKSPACE/$SKYSCAN_CACHE_DIR
          mkdir $GITHUB_WORKSPACE/$SKYSCAN_OUTPUT_DIR
          ./scripts/launch_scripts/launch_server.sh \
            --reco-algo millipede \
            --event-file $GITHUB_WORKSPACE/$REALTIME_EVENTS_DIR/${{ matrix.eventfile }} \
            --cache-dir $GITHUB_WORKSPACE/$SKYSCAN_CACHE_DIR \
            --output-dir $GITHUB_WORKSPACE/$SKYSCAN_OUTPUT_DIR \
            --startup-files-dir $GITHUB_WORKSPACE \
            --broker $PULSAR_ADDRESS \
            --log DEBUG \
            --log-third-party INFO \
            --mini-test-variations \
            --min-nside 1 \
            --max-nside 1 \
            &

          # wait until the mq-basename.txt file exists (with a timeout)
          endtime=$(date -ud "10 minutes" +%s)  # wait this long for server startup
          while [[ $(date -u +%s) -le $endtime ]]; do
            if [[ -e $GITHUB_WORKSPACE/mq-basename.txt && -e $GITHUB_WORKSPACE/baseline_GCD_file.txt && -e $GITHUB_WORKSPACE/GCDQp_packet.pkl ]]; then
              break
            fi
            echo "waiting for startup files..."
            sleep 5
          done

          cat $GITHUB_WORKSPACE/mq-basename.txt

          nclients=$(( $CLIENTS_PER_CPU * $(nproc) ))
          echo "Launching $nclients clients"
          mkdir $GITHUB_WORKSPACE/$SKYSCAN_DEBUG_DIR
          export PULSAR_UNACKED_MESSAGES_TIMEOUT_SEC=1800  # 30 mins
          for i in $( seq 1 $nclients ); do
            ./scripts/launch_scripts/launch_client.sh \
              --mq-basename $(cat $GITHUB_WORKSPACE/mq-basename.txt) \
              --baseline-gcd-file $(cat $GITHUB_WORKSPACE/baseline_GCD_file.txt) \
              --gcdqp-packet-pkl $GITHUB_WORKSPACE/GCDQp_packet.pkl \
              --broker $PULSAR_ADDRESS \
              --log DEBUG \
              --log-third-party INFO \
              --debug-directory $GITHUB_WORKSPACE/$SKYSCAN_DEBUG_DIR \
              &
            echo -e "\t$i clients launched"
          done

          wait -n  # for server
          for i in $( seq 1 $nclients ); do
            wait -n  # for client
          done
      - name: Test Output Against Known Result (.npz)
        run: |
          ls $GITHUB_WORKSPACE/$SKYSCAN_OUTPUT_DIR
          outfile=$(ls -d $GITHUB_WORKSPACE/$SKYSCAN_OUTPUT_DIR/*.npz)
          echo $outfile

          pip install .  # don't need icecube, so no docker container needed
          python $GITHUB_WORKSPACE/tests/compare_scan_results.py \
            --actual $outfile \
            --expected $GITHUB_WORKSPACE/tests/data/results_npz/$(basename $outfile) \
            --disqualify-zero-energy-pixels \
            --assert \
            || (cat $(ls *.diff.json) && false)

  test-run-pixel-reco:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: [
          "BRONZE",
          "GOLD",
          "JSON",
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Build Skymap Scanner Docker Image
        run: |
          ./tests/docker_scripts/docker_local_build.sh
      - name: Run
        run: |
          in_pkl=$(ls -d $GITHUB_WORKSPACE/tests/data/reco_pixel_pkls/${{ matrix.dir }}/*.in.pkl)
          ./tests/docker_scripts/_launch_reco_pixel.sh \
            in_pkl \
            $GITHUB_WORKSPACE/tests/data/reco_pixel_pkls/${{ matrix.dir }}/GCDQp_packet.pkl \
            $GITHUB_WORKSPACE/tests/data/reco_pixel_pkls/${{ matrix.dir }}/baseline_GCD_file.txt \
      - name: Test Output Against Known Result (.pkl)
        run: |
          ls $GITHUB_WORKSPACE/tests/data/reco_pixel_pkls
          out_pkl=$(ls -d $GITHUB_WORKSPACE/tests/data/reco_pixel_pkls/${{ matrix.dir }}/*.out.pkl)

          pip install .  # don't need icecube, so no docker container needed
          python $GITHUB_WORKSPACE/tests/compare_reco_pixel_pkl.py \
            --actual $GITHUB_WORKSPACE/tests/data/reco_pixel_pkls/${{ matrix.dir }}/out.pkl \
            --expected out_pkl \
            --diff-out-dir $GITHUB_WORKSPACE/tests/data/reco_pixel_pkls/${{ matrix.dir }} \
            --disqualify-zero-energy-pixels \
            --assert \
            || (cat $(ls $GITHUB_WORKSPACE/tests/data/reco_pixel_pkls/${{ matrix.dir }}/*.diff.json) && false)

