name: tests

on: [push]

env:
  DOCKERIZE_VERSION: v0.3.0

jobs:

  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/* .
          docker build --no-cache -t skyscan-cloud .

  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Pulsar Server Docker Container (starts up during skymap scanner image build)
        run: |
          docker run -i -d --rm -p 6650:6650 -p 8080:8080 --name pulsar_local apachepulsar/pulsar:2.6.0 /bin/bash -c "sed -i s/brokerDeleteInactiveTopicsEnabled=.*/brokerDeleteInactiveTopicsEnabled=false/ /pulsar/conf/standalone.conf && bin/pulsar standalone"
      - name: Build Skymap Scanner Docker Image
        run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/* .
          docker build --no-cache -t skyscan-cloud .
      - name: Configure Pulsar Server
        run: |
          wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          dockerize -wait tcp://localhost:8080 -timeout 1m
          dockerize -wait tcp://localhost:6650 -timeout 1m
          ./skymap_scanner/tests/docker_scripts/pulsar_config.sh pulsar_local
      - name: Run Test(s)
        run: |
          ./skymap_scanner/tests/docker_scripts/launch_all.sh skyscan-cloud http://icecube:skua@convey.icecube.wisc.edu/data/user/ckopper/event_HESE_2017-11-28.json

  test-producer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Pulsar Server Docker Container (starts up during skymap scanner image build)
        run: |
          docker run -i -d --rm -p 6650:6650 -p 8080:8080 --name pulsar_local apachepulsar/pulsar:2.6.0 /bin/bash -c "sed -i s/brokerDeleteInactiveTopicsEnabled=.*/brokerDeleteInactiveTopicsEnabled=false/ /pulsar/conf/standalone.conf && bin/pulsar standalone"
      - name: Build Skymap Scanner Docker Image
        run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/* .
          docker build --no-cache -t skyscan-cloud .
      - name: Configure Pulsar Server
        run: |
          wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          dockerize -wait tcp://localhost:8080 -timeout 1m
          dockerize -wait tcp://localhost:6650 -timeout 1m
          ./skymap_scanner/tests/docker_scripts/pulsar_config.sh pulsar_local
      - name: Run Test(s)
        run: |
          ./skymap_scanner/tests/docker_scripts/launch_producer.sh skyscan-cloud http://icecube:skua@convey.icecube.wisc.edu/data/user/ckopper/event_HESE_2017-11-28.json

  test-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Pulsar Server Docker Container (starts up during skymap scanner image build)
        run: |
          docker run -i -d --rm -p 6650:6650 -p 8080:8080 --name pulsar_local apachepulsar/pulsar:2.6.0 /bin/bash -c "sed -i s/brokerDeleteInactiveTopicsEnabled=.*/brokerDeleteInactiveTopicsEnabled=false/ /pulsar/conf/standalone.conf && bin/pulsar standalone"
      - name: Build Skymap Scanner Docker Image
        run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/* .
          docker build --no-cache -t skyscan-cloud .
      - name: Configure Pulsar Server
        run: |
          wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          dockerize -wait tcp://localhost:8080 -timeout 1m
          dockerize -wait tcp://localhost:6650 -timeout 1m
          ./skymap_scanner/tests/docker_scripts/pulsar_config.sh pulsar_local
      - name: Run Test(s)
        run: |
          ./skymap_scanner/tests/docker_scripts/launch_worker.sh skyscan-cloud

  test-collector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Pulsar Server Docker Container (starts up during skymap scanner image build)
        run: |
          docker run -i -d --rm -p 6650:6650 -p 8080:8080 --name pulsar_local apachepulsar/pulsar:2.6.0 /bin/bash -c "sed -i s/brokerDeleteInactiveTopicsEnabled=.*/brokerDeleteInactiveTopicsEnabled=false/ /pulsar/conf/standalone.conf && bin/pulsar standalone"
      - name: Build Skymap Scanner Docker Image
        run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/* .
          docker build --no-cache -t skyscan-cloud .
      - name: Configure Pulsar Server
        run: |
          wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          dockerize -wait tcp://localhost:8080 -timeout 1m
          dockerize -wait tcp://localhost:6650 -timeout 1m
          ./skymap_scanner/tests/docker_scripts/pulsar_config.sh pulsar_local
      - name: Run Test(s)
        run: |
          ./skymap_scanner/tests/docker_scripts/launch_collector.sh skyscan-cloud