name: tests

on: [push]

jobs:

  test-case-scan:
    runs-on: ubuntu-latest
    container:
      image: icecube/icetray
    steps:
      - uses: actions/checkout@v3
      - run: |
          whereis python
          which python
          which python3
          sudo -H pip install virtualenv
          printenv
          echo "---"
          python3 -m virtualenv -p python3 env
          . env/bin/activate
          echo "---"
          whereis python
          which python
          which python3
          printenv
          echo "---"
          cd test-case-scan/
          pip install -r requirements.txt
          ./scans.sh
          python create_plot.py ic191001a_sim -c output_skymap_scanner