name: tests

on: [push]

jobs:

  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/ .
          cp ../python/prepare_frames.py .
          docker build --no-cache -t skyscan-cloud .

  test-docker-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/ .
          cp ../python/prepare_frames.py .
          docker build --no-cache -t skyscan-cloud .
          docker run -p 6650:6650 skyscan-cloud