name: tests

on: [push]

jobs:

  test-case-scan:
    runs-on: ubuntu-latest
    container:
      image: icecube/icetray:combo-stable
      env:
        PYTHONPATH: /usr/local/icetray/lib
        PATH: /usr/local/icetray/bin:/usr/bin:/bin
        LD_LIBRARY_PATH: /usr/local/icetray/lib
        I3_BUILD: /usr/local/icetray
        I3_SRC: /usr/local/icetray
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd test-case-scan/
          ./scans.sh
          python create_plot.py ic191001a_sim -c output_skymap_scanner