name: tests

on: [push]

jobs:

  test-case-scan:
    runs-on: ubuntu-latest
    container:
      image: icecube/icetray
      env:
        PYTHONPATH: /usr/local/icetray/lib
        PATH: /usr/local/icetray/bin:/usr/bin:/bin
        LD_LIBRARY_PATH: /usr/local/icetray/lib
        I3_BUILD: /usr/local/icetray
        I3_SRC: /usr/local/icetray
    steps:
      - uses: actions/checkout@v3
      - run: |
          # /usr/local/icetray/env-shell.sh
          whereis python
          which python
          which python3
          # sudo -H pip install virtualenv
          printenv
          echo "---"
          # python3 -m virtualenv -p python3 env
          # . env/bin/activate
          echo "---"
          whereis python
          which python
          which python3
          printenv
          echo "---"
          pip freeze
          cd test-case-scan/
          pip install -r requirements.txt
          ./scans.sh
          python create_plot.py ic191001a_sim -c output_skymap_scanner