name: tests

on: [push]

jobs:

  without-docker:
    runs-on: ubuntu-latest
    container:
      image: icecube/icetray
      env:
        PYTHONPATH: /usr/local/icetray/lib
        PATH: /usr/local/icetray/bin:/usr/bin:/bin
        LD_LIBRARY_PATH: /usr/local/icetray/lib
        I3_BUILD: /usr/local/icetray
        I3_SRC: /usr/local/icetray
    steps:
      - uses: actions/checkout@v3
      - run: |
          # manually -- not using Dockerfile
          python cloud_tools/entrypoint.py