name: tests

on: [push]

env:
  PY_COLORS: "1"
  # SKYSCAN_TEST_EVENT: test_event_01
  # SKYSCAN_TEST_EVENT_PATH: /mnt/test_event_01.i3
  PULSAR_CONTAINER: pulsar_local
  SKYSCAN_CONTAINER: skyscan-cloud
  # SKYSCAN_EVENT: ./tests/docker_scripts/event_HESE_2017-11-28.json
  SKYSCAN_CACHE_DIR: cache-dir
  # SKYSCAN_EVENT: ic191001a_sim.i3
  SKYSCAN_EVENT_PKL: ./tests/data/skyscan_data/realtime_events/-243122034428012599.pkl
  SKYSCAN_GCD_DIR: /cvmfs/icecube.opensciencegrid.org/users/RealTime/GCD/PoleBaseGCDs/
  PULSAR_ADDRESS: localhost:6650
  PULSAR_AUTH: ""

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          ./tests/docker_scripts/docker_build.sh $SKYSCAN_CONTAINER

  test-run-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cvmfs-contrib/github-action-cvmfs@v2
      - name: Test CernVM-FS
        run: ls $SKYSCAN_GCD_DIR
      - name: Run Pulsar Server Docker Container (starts up during skymap scanner image build)
        run: |
          ./tests/docker_scripts/pulsar_run.sh $PULSAR_CONTAINER
      - name: Build Skymap Scanner Docker Image
        run: |
          ./tests/docker_scripts/docker_build.sh $SKYSCAN_CONTAINER
      - name: Configure Pulsar Server
        run: |
          ./tests/docker_scripts/pulsar_config.sh $PULSAR_CONTAINER
      - name: Run
        run: |
          # Based on cloud_tools README.md (with collector+saver merged into server)
          ./tests/docker_scripts/launch_server.sh $SKYSCAN_CONTAINER &
          ./tests/docker_scripts/launch_client.sh $SKYSCAN_CONTAINER &
      - name: Check Jobs
        run: |
          for job in server client ; do
            wait -n
            echo "$job: exit code $?"
            if [ $? -ne 0 ]; then
              exit $?
            fi
          done
      # - name: Test Output
      #   run: |
      #     # docker run --rm -v $PWD:/mnt -i icecube/icetray:combo-stable-prod dataio-shovel -l millipede /mnt/test_event_01.i3

  test-run-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cvmfs-contrib/github-action-cvmfs@v2
      - name: Test CernVM-FS
        run: ls $SKYSCAN_GCD_DIR
      - name: Run Pulsar Server Docker Container (starts up during skymap scanner image build)
        run: |
          ./tests/docker_scripts/pulsar_run.sh $PULSAR_CONTAINER
      - name: Build Skymap Scanner Docker Image
        run: |
          ./tests/docker_scripts/docker_build.sh $SKYSCAN_CONTAINER
      - name: Configure Pulsar Server
        run: |
          ./tests/docker_scripts/pulsar_config.sh $PULSAR_CONTAINER
      - name: Run
        run: |
          ./tests/docker_scripts/launch_server.sh $SKYSCAN_CONTAINER
      # - name: Test Output
      #   run: |

  test-run-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cvmfs-contrib/github-action-cvmfs@v2
      - name: Test CernVM-FS
        run: ls $SKYSCAN_GCD_DIR
      - name: Run Pulsar Server Docker Container (starts up during skymap scanner image build)
        run: |
          ./tests/docker_scripts/pulsar_run.sh $PULSAR_CONTAINER
      - name: Build Skymap Scanner Docker Image
        run: |
          ./tests/docker_scripts/docker_build.sh $SKYSCAN_CONTAINER
      - name: Configure Pulsar Server
        run: |
          ./tests/docker_scripts/pulsar_config.sh $PULSAR_CONTAINER
      - name: Run
        run: |
          ./tests/docker_scripts/launch_client.sh $SKYSCAN_CONTAINER
      # - name: Test Output
      #   run: |
