name: tests

on: [push]

jobs:

  test-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/ .
          cp ../python/prepare_frames.py .
          docker build --no-cache -t skyscan-cloud .