name: tests

on: [push]

jobs:

  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/* .
          docker build --no-cache -t skyscan-cloud .

  test-docker-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Set up Apache Pulsar
      #   uses: reugn/github-action-pulsar@v1

      - name: Build Skymap Scanner Docker Image
        run: |
          cd skymap_scanner/
          cp -r -n ../cloud_tools/* .
          docker build --no-cache -t skyscan-cloud .

      - name: Run Pulsar Server Docker Container & Configure
        run: |
          docker run -i -d --rm -p 6650:6650 -p 8080:8080 --name pulsar_local apachepulsar/pulsar:2.6.0 /bin/bash -c "sed -i s/brokerDeleteInactiveTopicsEnabled=.*/brokerDeleteInactiveTopicsEnabled=false/ /pulsar/conf/standalone.conf && bin/pulsar standalone"
          ./skymap_scanner/make_pulsar_server_config.sh pulsar_local

      - name: Run Test(s)
        run: |
          docker run -p 6650:6650 skyscan-cloud