name: tests

on: [push]

jobs:

  test-case-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      # - uses: docker://icecube/icetray
      - run: |
          docker run icecube/icetray
          cd test-case-scan/
          pip install -r requirements.txt
          ./scans.sh
          python create_plot.py ic191001a_sim -c output_skymap_scanner